[theme]
primaryColor="#ffffff"
backgroundColor="#ecf5f5"
secondaryBackgroundColor="#b1e1e1"
textColor="#000000"

[browser]
# Internet address where users should point their browsers in order to connect to the app. Can be IP address or DNS name and path.
# This is used to: - Set the correct URL for CORS and XSRF protection purposes. - Show the URL on the terminal - Open the browser
# Default: 'localhost'
serverAddress = "localhost"

# Whether to send usage statistics to Streamlit.
# Default: true
gatherUsageStats = true